// Domains that are social profiles / link hubs / messaging links, not real websites.
// Ported in spirit from Leadhunter_Pro config.py (MIT) — see THIRD_PARTY_NOTICES.md.
export const SOCIAL_DOMAINS: string[] = [
  "instagram.com",
  "facebook.com",
  "fb.com",
  "fb.me",
  "m.me",
  "linktr.ee",
  "linktree.com",
  "beacons.ai",
  "bio.link",
  "lnk.bio",
  "taplink.cc",
  "campsite.bio",
  "wa.me",
  "whatsapp.com",
  "api.whatsapp.com",
  "wa.link",
  "tiktok.com",
  "twitter.com",
  "x.com",
  "youtube.com",
  "youtu.be",
  "linkedin.com",
  "pinterest.com",
  "telegram.me",
  "t.me",
  "threads.net",
  "snapchat.com",
  "yelp.com",
  "tripadvisor.com",
  "ifood.com.br",
  "goo.gl",
  "g.page",
  "maps.app.goo.gl",
];
