"use client";

import { motion } from "framer-motion";
import { MapPin, Cpu, Send } from "lucide-react";

const container = {
  hidden: {},
  show: { transition: { staggerChildren: 0.1 } },
};
const item = {
  hidden: { opacity: 0, y: 16 },
  show: { opacity: 1, y: 0, transition: { duration: 0.4, ease: "easeOut" as const } },
};

const steps = [
  {
    num: "01",
    icon: MapPin,
    title: "Find leads",
    desc: "Enter your target industry and city. Prospex scrapes Google Maps and scores each business using AI — rating, website presence, location value, and more.",
    color: "text-purple-400",
    border: "border-purple-500/30",
    bg: "bg-purple-500/10",
  },
  {
    num: "02",
    icon: Cpu,
    title: "AI analyzes & creates content",
    desc: "Each HIGH-priority lead gets personalized outreach content generated by AI: email, WhatsApp message, Instagram DM, LinkedIn note, and cold call script.",
    color: "text-blue-400",
    border: "border-blue-500/30",
    bg: "bg-blue-500/10",
  },
  {
    num: "03",
    icon: Send,
    title: "Reach out & close deals",
    desc: "Use the built-in CRM to track conversations, schedule follow-ups, and move leads through your pipeline from New to Won.",
    color: "text-emerald-400",
    border: "border-emerald-500/30",
    bg: "bg-emerald-500/10",
  },
];

export function HowItWorks() {
  return (
    <section id="how-it-works" className="py-24 px-4 sm:px-6 bg-white/[0.01] border-y border-white/5">
      <div className="max-w-5xl mx-auto">
        <div className="text-center mb-16">
          <span className="text-purple-400 text-sm font-semibold uppercase tracking-wider">How it works</span>
          <h2 className="text-3xl sm:text-4xl font-bold text-white mt-3 mb-4">
            From zero to outreach in minutes
          </h2>
          <p className="text-slate-400 max-w-lg mx-auto text-sm">
            No complex setup. Just configure your API key and start finding leads.
          </p>
        </div>

        <motion.div
          variants={container}
          initial="hidden"
          whileInView="show"
          viewport={{ once: true, amount: 0.2 }}
          className="grid grid-cols-1 md:grid-cols-3 gap-6"
        >
          {steps.map((step) => (
            <motion.div
              key={step.num}
              variants={item}
              className={`bg-white/[0.03] border ${step.border} rounded-2xl p-6 hover:bg-white/[0.05] transition-colors`}
            >
              <div className="flex items-center gap-3 mb-4">
                <div className={`w-10 h-10 rounded-xl ${step.bg} flex items-center justify-center flex-shrink-0`}>
                  <step.icon className={`w-5 h-5 ${step.color}`} />
                </div>
                <span className="text-2xl font-bold text-white/20">{step.num}</span>
              </div>
              <h3 className="text-white font-semibold mb-2">{step.title}</h3>
              <p className="text-slate-400 text-sm leading-relaxed">{step.desc}</p>
            </motion.div>
          ))}
        </motion.div>
      </div>
    </section>
  );
}
